name: MessageME

on: push

jobs:
  msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install thingz
        run: sudo apt install -y clang-tidy clang-format inkscape ghostscript
      - name : make flags
        run: |
          curl https://img.shields.io/badge/test-passing-green -o good-flag.svg
          curl https://img.shields.io/badge/test-failed-red -o bad-flag.svg
          inkscape good-flag.svg --export-png=good-flag.png
          inkscape bad-flag.svg --export-png=bad-flag.png
      - name: Compile
        run: |
          echo -ne "# Il y a eu une erreur de compilation !\n\n" >> output.md
          echo "color=12000000" >> $GITHUB_ENV
          mv bad-flag.png flag.png
          eval "make re"
          makecode=$?
          ./mouliVD/script
          testcode=$?
          if (((makecode == 0) && (testcode == 0)))
          then
            echo -ne "# Aucune erreur de compilation\n\n" > output.md
            echo "color=651525" >> $GITHUB_ENV
            rm flag.png
            mv good-flag.png flag.png
          fi
          web=`cat webhook`
          echo $web
      - name: Coding Style
        run: |
          echo "$(python3 abricot.py)" >> output.md
      - name: Discord notification
        if: always()
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: $web
          embed-title: "Voici le résultat de votre moulinette :"
          embed-color: ${{ env.color }}
          filename: output.md
          username: "Normeur"
      - name: mouli message
        if: always()
        uses: tsickert/discord-webhook@v4.0.0
        with:
          username: "Normeur"
          webhook-url: $web
          filename: flag.png
