name: MessageME

on: push

jobs:
  msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install thingz
        run: sudo apt install -y clang-tidy clang-format inkscape tcsh
      - name : make flags
        run: |
          curl https://img.shields.io/badge/test-passing-green -o good-flag.svg
          curl https://img.shields.io/badge/test-failed-red -o bad-flag.svg
          inkscape good-flag.svg --export-png=good-flag.png
          inkscape bad-flag.svg --export-png=bad-flag.png
      - name: get-wehook
        run : |
          web=`cat weblink`
          echo "hook=$web" >> $GITHUB_ENV
      - name: Compile_and_test
        run: |
          echo "color=16711680" >> $GITHUB_ENV
          mv bad-flag.png flag.png
          eval "make re"
          makecode=$?
          ./mouliVD/script
          testcode=$?
          echo $testcode
          if (((makecode == 0) && (testcode == 0)))
          then
            echo "color=651525" >> $GITHUB_ENV
            rm flag.png
            mv good-flag.png flag.png
          fi
      - name: Ardorax Coding Style and Discord
        if: always()
        uses: Ardorax/EpitechStyle@latest
        with:
          URL: ${{ env.hook }}
          COLOR: ${{ env.color }}
      - name: mouli message
        if: always()
        uses: tsickert/discord-webhook@v4.0.0
        with:
          username: "Normeur"
          webhook-url: ${{ env.hook }}
          filename: flag.png
